config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:show]

  namespace :admin do
    root 'application#index'

    resources :klasses, except: [:show]
    resources :students, only: [:index, :destroy] do
      collection do
        get :search
        post :search
      end
    end
    resources :rules, only: [:index, :edit, :update] do
      collection do
        get :edit_ability
        post :update_ability
      end
    end
    resources :statistics, only: [:index]
    resources :teachers, except: [:show]
    resources :notifications, except: [:index, :show]
  end

  devise_for :users
  root 'welcome#index'
  get "rule" => "rule#index"

  resources :klasses, only: [:show] do
    resources :students, except: [:index, :destroy] do
      resources :scores, only: [:edit, :update]
    end

    resources :semesters, only: [] do
      resources :courses, only: [] do
        resources :details, only: [:index, :edit, :update] do
          member do
            patch :reset
          end

          collection do
            get :edit_all
            post :update_all

            patch :reset_all
          end
        end
      end
    end
  end

  resources :teachers, only: [:show]

end

app/models/rule.rb
class Rule < ActiveRecord::Base
end

app/controllers/admin/rules_controller.rb
class Admin::RulesController < Admin::ApplicationController
  def index
    @rule = Rule.first
  end

  def edit
    @rule = Rule.find(params[:id])
    @attr = params[:attr]
  end

  def update
    @rule = Rule.find(params[:id])
    rule_params = params.require(:rule).permit(:max_quantity, :min_age,
      :max_age, :min_point, :max_point)

    if @rule.update(rule_params)
      flash[:notice] = "Rule has been successfully updated."
      redirect_to admin_rules_path
    else
      flash.now[:alert] = "Rule has not been successfully updated."
      render :edit
    end
  end

  def edit_ability
    @marks = Mark.all
    @conducts = Conduct.all
  end

  def update_ability
    marks_params = params.require(:update_ability).require(:marks).permit!
    results = Mark.update(marks_params.keys,
      marks_params.values).reject { |m| m.errors.empty? }

    if results.empty?
      flash[:notice] = "Rule has been successfully updated."
      redirect_to admin_rules_path
    else
      flash.now[:alert] = "Rule has not been successfully updated."
      @marks = Mark.all - results + results
      @conducts = Conduct.all
      render :edit_ability
    end

  end
end

app/controllers/rule_controller.rb
class RuleController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
    @rule = Rule.first
  end
end

app/helpers/admin/rules_helper.rb
module Admin::RulesHelper
end

app/helpers/rule_helper.rb
module RuleHelper
end

app/views/admin/rules/_form.html.erb
<%= simple_form_for [:admin, @rule] do |f| %>
  <% if @attr.nil? || @attr.include?("max_quantity") %>
    <%= f.input :max_quantity, label: "Số lượng học sinh tối đa mỗi lớp" %>
  <% end %>
  <% if @attr.nil? || @attr.include?("min_age") %>
    <%= f.input :min_age, label: "Tuổi tối thiểu" %>
    <%= f.input :max_age, label: "Tuổi tối đa" %>
  <% end %>
  <% if @attr.nil? || @attr.include?("min_point") %>
    <%= f.input :min_point, label: "Điểm tối thiểu" %>
    <%= f.input :max_point, label: "Điểm tối đa" %>
  <% end %>

  <%= f.button :submit, value: "Cập nhật", class: "btn-success" %>
<% end %>

app/views/admin/rules/edit.html.erb
<%= title("Chỉnh sửa Quy định chung") %>

<header>
  <h2>Chỉnh sửa Quy định chung</h2>
</header>



<%= render "form" %>

<header></header>
<%= link_to "Trở về", admin_rules_path, class: "back" %>

app/views/admin/rules/edit_ability.html.erb
<%= title("Chỉnh sửa Quy định Danh hiệu") %>

<header>
  <h2 class="maw100">Chỉnh sửa Quy định Danh hiệu</h2>
</header>

<div class="listing-index">
  <%= simple_form_for :update_ability,
  url: update_ability_admin_rules_path, method: :post,
  html: { class: "center full_width" } do |f|%>
  <table>
    <thead>
      <tr>
        <th>Danh hiệu</th>
        <% @marks.each do |mark| %>
          <td><%= mark.name %></td>
        <% end %>
      </tr>
    </thead>
      <tbody>
        <tr>
          <th class="center">Học lực <span class="tiny">(Trở lên)</span></th>
          <% @marks.each do |mark| %>
            <%= f.simple_fields_for "marks[]", mark do |m| %>
              <td class="input-score"><%= m.input :point, label: false %></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <th class="center">Hạnh kiểm <span class="tiny">(Trở lên)</span></th>
          <% @conducts.each do |conduct| %>
            <td><%= conduct.name %></td>
          <% end %>
        </tr>
      </tbody>
    </table>

    <%= f.button :submit, value: "Cập nhật", class: "btn-success" %>
  <% end %>
</div>


<header></header>
<%= link_to "Trở về", admin_rules_path, class: "back" %>

app/views/admin/rules/index.html.erb
<%= title("Quy định") %>

<header>
  <h2>Quy định</h2>
</header>

<div class="row">
  <div class="col-md-6">
    <header>
      <h4>Quy định chung</h4>
      <ul class="actions">
        <li>
          <%= link_to "Sửa tất cả", [:edit, :admin, @rule], class: "edit" %>
        </li>
      </ul>
    </header>

    <table class="bdbtable maw100">
      <tbody>
        <tr>
          <td><strong>Số lượng học sinh tối đa mỗi lớp</strong>: 
            <b><%= @rule.max_quantity %></b>
          </td>
          <td>
            <%= link_to 'Sửa', { "controller"=>"admin/rules", "action"=>"edit", "id"=>"1", "attr": "max_quantity" }, class: "edit" %>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Số tuổi được phép</strong>: <br/>
            <ul>
              <li>Tuổi tối thiểu: <b><%= @rule.min_age %></b></li>
              <li>Tuổi tối đa: <b><%= @rule.max_age %></b></li>
            </ul>
          </td>
          <td>
            <%= link_to 'Sửa', { "controller"=>"admin/rules", "action"=>"edit", "id"=>"1", "attr": "min_age" }, class: "edit" %>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Điểm số được phép</strong>: <br/>

            <ul>
              <li>Điểm tối thiểu: <b><%= @rule.min_point %></b></li>
              <li>Điểm tối đa: <b><%= @rule.max_point %></b></li>
            </ul>
          </td>
          <td>
            <%= link_to 'Sửa', { "controller"=>"admin/rules", "action"=>"edit", "id"=>"1", "attr": "min_point" }, class: "edit" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="col-md-6">
    <header>
      <h4>Quy định Danh hiệu</h4>

      <ul class="actions">
        <li>
          <%= link_to "Sửa", edit_ability_admin_rules_path, class: "edit" %>
        </li>
      </ul>
    </header>

    <div class="listing-index">
      <table>
        <thead>
          <tr>
            <th>Học lực</th>
            <th>Hạnh kiểm</th>
            <th>Danh hiệu</th>
          </tr>
        </thead>
        <tbody>
          <% Mark.all.each_with_index do |mark, index| %>
            <tr>
              <td><%= mark.name %><br/><span class="tiny">(<%= mark.point %> Trở lên)</span></td>
              <td><%= Conduct.find(index + 1).name %>
              <br/><span class="tiny">(Trở lên)</span></td>
              <td><%= mark.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<header></header>
<%= link_to "Trở về", admin_root_path, class: "back" %>