config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:show]

  namespace :admin do
    root 'application#index'

    resources :klasses, except: [:show]
    resources :students, only: [:index, :destroy] do
      collection do
        get :search
        post :search
      end
    end
    resources :rules, only: [:index, :edit, :update] do
      collection do
        get :edit_ability
        post :update_ability
      end
    end
    resources :statistics, only: [:index]
    resources :teachers, except: [:show]
    resources :notifications, except: [:index, :show]
  end

  devise_for :users
  root 'welcome#index'
  get "rule" => "rule#index"

  resources :klasses, only: [:show] do
    resources :students, except: [:index, :destroy] do
      resources :scores, only: [:edit, :update]
    end

    resources :semesters, only: [] do
      resources :courses, only: [] do
        resources :details, only: [:index, :edit, :update] do
          member do
            patch :reset
          end

          collection do
            get :edit_all
            post :update_all

            patch :reset_all
          end
        end
      end
    end
  end

  resources :teachers, only: [:show]

end

app/controllers/admin/klasses_controller.rb
class Admin::KlassesController < Admin::ApplicationController
  before_action :set_klass, only: [:edit, :update, :destroy]

  # GET /admin/klasses
  def index
    @klasses = Klass.all
  end

  # GET /admin/klasses/new
  def new
    @klass = Klass.new
  end

  # GET /admin/klasses/1/edit
  def edit
  end

  # POST /admin/klasses
  def create
    @klass = Klass.new(klass_params)

    if @klass.save
      flash[:notice] = "Class was successfully created."
      redirect_to @klass
    else
      flash.now[:alert] = "Class was not successfully created."
      render :new
    end
  end

  # PATCH/PUT /admin/klasses/1
  def update
    if @klass.update(klass_params)
      # @klass.attributes = params.require(:klass).permit(:teacher)
      flash[:notice] = "Class was successfully updated"
      redirect_to @klass
    else
      flash.now[:alert] = "Class was not successfully updated"
      render :edit
    end
  end

  # DELETE /admin/klasses/1
  def destroy
    @klass.destroy
    flash[:notice] = "Class was successfully destroyed."
    redirect_to admin_klasses_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klass
      @klass = Klass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klass_params
      params.require(:klass).permit(:name, :grade_id, :teacher_id)
    end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
	def show
		@klass = Klass.find(params[:id])
    @q = @klass.students.order(:first_name).ransack(params[:q])
		@students = @q.result(distinct: true)
	end
end

app/helpers/klasses_helper.rb
module KlassesHelper
  def max_students?(klass)
    max_students = Rule.find(1).max_quantity
    klass.students.count == max_students
  end
end

app/views/admin/klasses/_form.html.erb
<%= simple_form_for [:admin, klass] do |f| %>
  <%= f.input :name, label: "Tên Lớp" %>
  <%= f.association :grade, include_blank: false, label: "Lớp" %><br/>
  <%= f.input :teacher_id, collection: Teacher.all,
    label: "Giáo viên chủ nhiệm" %><br/>

  <%= f.button :submit, value: klass.new_record? ? "Tạo Lớp" : "Cập nhật",
  	class: "btn-success" %>
<% end %>

app/views/admin/klasses/edit.html.erb
<%= title("Chỉnh sửa Lớp") %>

<header>
	<h2>Chỉnh sửa Lớp</h2>
</header>

<%= render 'form', klass: @klass %>

<%= link_to 'Trở về', :back, class: "back" %>

app/views/admin/klasses/index.html.erb
<%= title("Danh sách Lớp") %>

<header>
  <h2>Danh sách Lớp</h2>

  <ul class="actions">
    <li><%= link_to "Thêm mới", new_admin_klass_path,
      class: "new" %></li>
  </ul>
</header>

<% if @klasses.present? %>
  <div class="listing-index">
    <table>
      <thead>
        <tr>
          <th>STT</th>
          <th>Lớp</th>
          <th>Khối</th>
          <th>Tổng số học sinh</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @klasses.each_with_index do |klass, index| %>
        <tr>
          <td><%= link_to index + 1, klass %></td>
          <td><%= klass.name %></td>
          <td><%= klass.grade.name %></td>
          <td><%= klass.students_count %></td>
          <td><%= link_to 'Sửa', [:edit, :admin, klass], class: "edit" %>
          <%= link_to 'Xóa', [:admin, klass], method: :delete, data: { confirm: 'Bạn đã chắc chưa?' }, class: "delete" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>Hiện tại chưa có dữ liệu.</p>
<% end %>

<header></header>
<%= link_to "Trở về", admin_root_path, class: "back" %>

app/views/admin/klasses/new.html.erb
<%= title("Thêm mới Lớp") %>
<header>
	<h2>Thêm mới Lớp</h2>
</header>

<%= render 'form', klass: @klass %>

<%= link_to 'Trở về', :back, class: "back" %>