config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:show]

  namespace :admin do
    root 'application#index'

    resources :klasses, except: [:show]
    resources :students, only: [:index, :destroy] do
      collection do
        get :search
        post :search
      end
    end
    resources :rules, only: [:index, :edit, :update] do
      collection do
        get :edit_ability
        post :update_ability
      end
    end
    resources :statistics, only: [:index]
    resources :teachers, except: [:show]
    resources :notifications, except: [:index, :show]
  end

  devise_for :users
  root 'welcome#index'
  get "rule" => "rule#index"

  resources :klasses, only: [:show] do
    resources :students, except: [:index, :destroy] do
      resources :scores, only: [:edit, :update]
    end

    resources :semesters, only: [] do
      resources :courses, only: [] do
        resources :details, only: [:index, :edit, :update] do
          member do
            patch :reset
          end

          collection do
            get :edit_all
            post :update_all

            patch :reset_all
          end
        end
      end
    end
  end

  resources :teachers, only: [:show]

end

app/controllers/admin/klasses_controller.rb
class Admin::KlassesController < Admin::ApplicationController
  before_action :set_klass, only: [:edit, :update, :destroy]

  # GET /admin/klasses
  def index
    @klasses = Klass.all
  end

  # GET /admin/klasses/new
  def new
    @klass = Klass.new
  end

  # GET /admin/klasses/1/edit
  def edit
  end

  # POST /admin/klasses
  def create
    @klass = Klass.new(klass_params)

    if @klass.save
      flash[:notice] = "Class was successfully created."
      redirect_to @klass
    else
      flash.now[:alert] = "Class was not successfully created."
      render :new
    end
  end

  # PATCH/PUT /admin/klasses/1
  def update
    if @klass.update(klass_params)
      # @klass.attributes = params.require(:klass).permit(:teacher)
      flash[:notice] = "Class was successfully updated"
      redirect_to @klass
    else
      flash.now[:alert] = "Class was not successfully updated"
      render :edit
    end
  end

  # DELETE /admin/klasses/1
  def destroy
    @klass.destroy
    flash[:notice] = "Class was successfully destroyed."
    redirect_to admin_klasses_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klass
      @klass = Klass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klass_params
      params.require(:klass).permit(:name, :grade_id, :teacher_id)
    end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
	def show
		@klass = Klass.find(params[:id])
    @q = @klass.students.order(:first_name).ransack(params[:q])
		@students = @q.result(distinct: true)
	end
end

app/helpers/klasses_helper.rb
module KlassesHelper
  def max_students?(klass)
    max_students = Rule.find(1).max_quantity
    klass.students.count == max_students
  end
end

app/views/klasses/show.html.erb
<% title("Lớp #{@klass.name}") %>

<header>
	<h2>Lớp <%= @klass.name %></h2>
  <% admins_only do %>
	<ul class="actions">
		<li><%= link_to 'Sửa Lớp', edit_admin_klass_path(@klass), class: "edit" %></li>
		<li><%= link_to "Xóa Lớp", admin_klass_path(@klass),
			class: "delete", method: :delete,
			data: { confirm: "Bạn đã chắc chưa?" } %></li>
	</ul>
  <% end %>
</header>

<table class="info">
	<tr>
		<th>Tên lớp</th>
		<td><%= @klass.name.upcase %></td>
	</tr>
	<tr>
		<th>Tên khối</th>
		<td><%= @klass.grade.name %></td>
	</tr>
	<tr>
		<th>Tổng số học sinh</th>
		<td><%= @klass.students_count %></td>
	</tr>
	<tr>
		<th>Giáo viên chủ nhiệm</th>
		<td><%= link_to @klass.teacher_name, @klass.teacher %></td>
	</tr>
	<tr>
		<th>Ngày tạo</th>
		<td><%= format_date(@klass.created_at) %></td>
	</tr>
	<tr>
		<th>Cập nhật lần cuối</th>
		<td><%= format_date(@klass.updated_at) %></td>
	</tr>
</table>

<header>
	<h3>Danh sách học sinh</h3>
  <div class="search-div">
    <%= search_form_for @q, url: @klass,
      html: { class: "form-inline" } do |f| %>
    <%= f.search_field :student_code_or_first_name_or_last_name_cont,
      class: "form-control", placeholder: "Nhập Tên, MSSV, ..." %>
    
    <button class='btn btn-search'>
      Tìm kiếm
    </button>
  <% end %>
  </div>
  
  <% if is_admin? || is_teacher? %>
  	<ul class="actions">
      <li><%= link_to "Bảng điểm",
      	klass_semester_course_details_path(@klass, Semester.first, Course.first),
      	class: "scoreboard" %></li>

      <% unless max_students?(@klass) %>
  		  <li><%= link_to "Thêm mới", new_klass_student_path(@klass),
          class: "new" %></li>
      <% end %>
  	</ul>
  <% end %>
</header>

<% if @students.present? %>
  <div class="listing-index icon-only">
    <table>
      <thead>
        <tr>
        	<th>STT</th>
		      <th><%= sort_link(@q, :first_name, "Họ và tên") %></th>
		      <th><%= sort_link(@q, :student_code, "Mã số học sinh") %></th>
          <% if is_admin? || is_teacher? %>
  		      <th>ĐTB HK1</th>
  		      <th>ĐTB HK2</th>
            <th><%= sort_link(@q, :student_code, "ĐTB Cả năm") %></th>
  		      <th></th>
          <% end %>
		    </tr>
      </thead>
      <tbody>
        <% @students.each_with_index do |student, index| %>
        <tr>
          <% if is_admin? || is_teacher? %>
            <td><%= link_to index + 1, [@klass, student] %></td>
          <% else %>
        	 <td><%= index + 1 %></td>
          <% end %>
	        <td><%= student.name %></td>
	        <td><%= student.student_code %></td>
          <% if is_admin? || is_teacher? %>
  	        <td><%= student.semester_gpa(Semester.find(1)) %></td>
  	        <td><%= student.semester_gpa(Semester.find(2)) %></td>
            <td><%= student.to_ability %></td>
  	        <td>
  	        	<%= link_to '', [:edit, @klass, student], class: "edit" %>
  	        	<%= link_to '', [:admin, student], method: :delete,
  	        	data: { confirm: 'Bạn đã chắc chưa?' }, class: "delete" %></td>
          <% end %>
	      </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>Hiện tại chưa có dữ liệu.</p>
<% end %>
	
<header></header>
<%= link_to "Trở về", admin_klasses_path, class: "back" %>